routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Done up to 18-A-User-Can-Favorite-Any-Reply

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');


// Route::resource('/threads', 'ThreadController');
Route::get('/threads', 'ThreadController@index');

Route::get('/threads/create', [
	'as' => 'create.thread',
	'uses' => 'ThreadController@create'
]);

Route::post('/threads', 'ThreadController@store');

Route::get('/threads/{channel}/{thread}', 'ThreadController@show');

Route::post('/threads/{channel}/{thread}/replies', 'ReplyController@store');

Route::get('/threads/{channel}', 'ThreadController@index');

Route::post('/replies/{reply}/favourite', 'FavouriteController@store');

Route::get('profile/{user}', 'ProfileController@show')->name('profile');

Route::delete('threads/{channel}/{thread}', 'ThreadController@destroy');

app/Thread.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Acivity;

class Thread extends Model
{
    use Traits\RecordActivity;
    protected $guarded = [];

    protected $with = ['creator', 'channel'];

    protected static function boot() 
    {
        parent::boot();

        static::addGlobalScope('replyCount', function ($builder) {
            $builder->withCount('replies');
        });

        static::deleting(function($thread) {
            $thread->replies->each->delete();
        });
    }

    public function path()
    {
        return "/threads/{$this->channel->slug}/{$this->id}";
    }

    public function replies()
    {
    	return $this->hasMany('App\Reply')
            ->with('owner');
    }

    public function creator()
    {
    	return $this->belongsTo('App\User', 'user_id');
    }

    public function addReply($reply)
    {
        $this->replies()->create($reply);
    }

    public function channel()
    {
        return $this->belongsTo('App\Channel');
    }

    public function scopeFilter($query, $filters)
    {
        return $filters->apply($query);
    }

}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Thread;
use Illuminate\Http\Request;
use App\Channel;
use App\User;
use App\Filters\ThreadFilters;

class ThreadController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->only(['store', 'create', 'destroy']);
    }

    public function getThreads($channel, $filters)
    {
        $threads = Thread::latest()->filter($filters);        

        if($channel->exists) {
            $threads->where('channel_id', $channel->id);
        }

        // Filters down according to the filter and get me the result
        $threads = $threads->get();

        return $threads;        
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Channel $channel, ThreadFilters $filters)
    {
        $threads = $this->getThreads($channel, $filters);

        if(request()->wantsJson()) {
            return $threads;
        }

        return view('threads.index', compact('threads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('threads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'body' => 'required',
            'channel_id' => 'required|exists:channels,id'
        ]);

        $thread = Thread::create([
            'user_id' => auth()->id(),
            'channel_id' => request('channel_id'),
            'title' => request('title'),
            'body' => request('body')
        ]);

        return redirect($thread->path())
            ->with('flash', 'Thread Created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function show($channel, Thread $thread)
    {
        // return $thread;
        return view('threads.show',[
            'thread'  => $thread,
            'replies' => $thread->replies()->paginate(5)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function edit(Thread $thread)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Thread $thread)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function destroy($channel, Thread $thread)
    {
        // if($thread->user_id != auth()->id()) {
        //     abort(403, 'You do not have correct priviliges to perform the action');
        // }

        $this->authorize('update', $thread);

        $thread->delete();


        if(request()->wantsJson()) {
            return response([], 204);
        }

        return redirect('/threads');
    }

}

resources/views/threads/create.blade.php
\@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Create Thread</div>
                <div class="panel-body">
                    {!! Form::open(['method' => 'post', 'url' => '/threads']) !!}
                        <div class="form-group">
                            {!! Form::label('channel_id', 'Choose a Channel') !!}
                            <select name='channel_id' id='channel_id' class='form-control' required>
                                <option>Choose Channel</option>
                                @foreach($channels as $channel)
                                    <option value={{ $channel->id }} class='form-control' 
                                        {{ old('channel_id') == $channel->id ? 'selected' : ''}}
                                    >
                                        {{ $channel->name }}
                                    </option>
                                @endforeach    
                            </select>      
                        </div>                     
                        <div class="form-group">
                            {!! Form::label('title',null,  ['class' => 'control-label']) !!}
                            {!! Form::text('title',null,  ['class' => 'form-control', 'placeholder' => 'Thread Title', 'value' => "{{ old('title') }}", 'required']) !!}
                        </div>
                        <div class="form-group">
                            {!! Form::label('Description',null,  ['class' => 'control-label']) !!}
                            <textarea rows = '5' name = 'body' class = 'form-control' placeholder = 'This sounds more appropriate!!' required>{{ old('body') }}</textarea>
                        </div>
                       
                        <div class="form-group">                    
                            <button type="submit" class = 'btn btn-default'>Submit</button>
                        </div>
                        @if(count($errors))
                            <ul class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif                      
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                @forelse($threads as $thread)
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="level">
                                <h4 class='flex'>
                                    <a href='{{ $thread->path() }}'>{{ $thread->title }}</a>
                                </h4>  
                                <a href = {{ $thread->path() }} >
                                    {{ $thread->replies_count }}
                                    {{ str_plural('reply', $thread->replies_count) }}
                                </a>                      
                            </div>
                        </div>
                        <div class="panel-body">
                            <article>

                                <div class="body">{{ $thread->body }}</div>
                            </article>
                            <hr>
                        </div>
                    </div>
                @empty
                    No Relevant Threads at the moment   
                @endforelse
            </div>
        </div>
    </div>
@endsection

resources/views/threads/reply.blade.php
<div id = 'reply-{{ $reply->id }}' class="panel panel-default">
     <div class="panel-heading">
     	<div class="level">
	     	<h5 class="flex">
		     	<a href = "{{ route('profile', $reply->owner) }}">{{ $reply->owner->name }}</a>
		     	 said {{ $reply->created_at->diffForHumans() }}
		    </h5>
		    <div>
				<form method='post' action="/replies/{{ $reply->id }}/favourite">
					{{ csrf_field() }}
					<button type='submit' class='btn btn-default' {{ $reply->isFavourited() ? 'disabled' : '' }}>
						{{ $reply->favourites_count }}
						Like
					</button>					
				</form>
		    </div> 		
     	</div>

     </div>
        <div class="panel-body">
            {{ $reply->body }}
            <hr>
     </div>
</div>

resources/views/threads/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="level">
                            <span class="flex">
                                <a href = "{{ route('profile', $thread->creator) }}">
                                    {{ $thread->creator->name }}
                                </a> posted {{ $thread->title }}                                
                            </span>
                            @can('update', $thread)
                                <form action={{ $thread->path() }} method='POST'>
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button type='submit' class='btn btn-link'>Delete</button>
                                </form>

                            @endcan    
                        </div>    
                    </div>
                    <div class="panel-body">
                        {{ $thread->body }}
                    </div>
                </div>
                <hr>
                @foreach($replies as $reply)
                    @include('threads.reply')
                @endforeach

                {{ $replies->links() }}

                @if(auth()->check())
                    {!! Form::open(['method' => 'post', 'url' => $thread->path() . '/replies']) !!}
                    {{-- {!! Form::token() !!} --}}
                        <div class="form-group">
                            <textarea rows = '5' name = 'body' class = 'form-control' placeholder = 'This sounds more appropriate!!'></textarea>
                        </div>
                        <button type="submit" class = 'btn btn-default'>Submit</button>
                    {!! Form::close() !!}
                @else
                    <p class='text-center'><a href = '{{ route('login') }}'>Please sign</a> in to participate</p>
                @endif             
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        This thread was published at {{ $thread->created_at->diffForHumans() }}
                        By <a href = '#'>{{ $thread->creator->name }}</a><p>
                        {{ $thread->replies_count }} {{ str_plural('comment', $thread->replies_count) }}

                    </div>
                </div>                        
            </div>
        </div>       
    </div>
@endsection